package toodoo.parser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import toodoo.exceptions.DateTimeConflictException;
import toodoo.exceptions.EmptyDeadlineException;
import toodoo.exceptions.EmptyDescriptionException;
import toodoo.exceptions.EmptyFromException;
import toodoo.exceptions.EmptyIndexException;
import toodoo.exceptions.EmptyRegexException;
import toodoo.exceptions.EmptyToException;
import toodoo.exceptions.IndexDoesNotExistException;
import toodoo.exceptions.TaskAlreadyMarkedException;
import toodoo.exceptions.TaskAlreadyUnmarkedException;
import toodoo.exceptions.UnknownKeywordException;
import toodoo.tasklist.TaskList;

/**
 * The Parser is used by TooDoo to receive and process the input by the user.
 */
public class Parser {

    /**
     * Returns a String representing the Keyword of the user's input.
     * @param userInputStrings An array containing the words in the user's input.
     * @return The keyword (first word) of the user's input.
     */
    public String getKeyWord(String[] userInputStrings) {
        return userInputStrings[0];
    }

    /**
     * Processes the user's input and returns the response string.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @param userInput The user's input string.
     * @return The response string generated by the command.
     */
    public String processUserInput(TaskList taskList, String userInput) {
        Keyword keyword;
        String[] splitUserInput = userInput.split(" ");
        String firstWord = splitUserInput[0];

        assert taskList != null : "TaskList should not be null";
        assert userInput != null : "User input should not be null";
        assert splitUserInput.length > 0 : "Input array should not be empty";

        try {
            keyword = Keyword.valueOf(firstWord.toUpperCase());
        } catch (IllegalArgumentException e) {
            keyword = Keyword.UNKNOWN;
        }

        try {
            switch (keyword) {
            case BYE:
                return "exit";
            case LIST:
                return taskList.toString();
            case MARK:
                return handleMark(splitUserInput, taskList);
            case UNMARK:
                return handleUnmark(splitUserInput, taskList);
            case TODO:
                String processedToDoString = this.processToDoString(splitUserInput);

                assert processedToDoString != null : "Processed ToDo string should not be null";

                return taskList.addToDo(processedToDoString);
            case DEADLINE:
                String[] processedDeadlineString = this.processDeadlineString(splitUserInput);

                assert processedDeadlineString.length == 2 : "Deadline should return 2 elements";

                return taskList.addDeadline(processedDeadlineString[0], processedDeadlineString[1]);
            case EVENT:
                String[] processedEventString = this.processEventString(splitUserInput);

                assert processedEventString.length == 3 : "Event should return 3 elements";

                return taskList.addEvent(processedEventString[0], processedEventString[1], processedEventString[2]);
            case DELETE:
                return handleDelete(splitUserInput, taskList);
            case FIND:
                return handleFind(splitUserInput, taskList);
            case UNKNOWN:
                throw new UnknownKeywordException(firstWord);
            default:
                throw new UnknownKeywordException(firstWord);
            }

        } catch (UnknownKeywordException e) {
            return e.getMessage();
        } catch (EmptyDescriptionException e) {
            return e.getMessage();
        } catch (EmptyDeadlineException e) {
            return e.getMessage();
        } catch (EmptyFromException e) {
            return e.getMessage();
        } catch (EmptyToException e) {
            return e.getMessage();
        } catch (EmptyRegexException e) {
            return e.getMessage();
        } catch (EmptyIndexException e) {
            return e.getMessage();
        } catch (DateTimeConflictException e) {
            return e.getMessage();
        } catch (IndexDoesNotExistException e) {
            return e.getMessage();
        } catch (TaskAlreadyMarkedException e) {
            return e.getMessage();
        } catch (TaskAlreadyUnmarkedException e) {
            return e.getMessage();
        } catch (NumberFormatException e) {
            return "Please provide a valid integer for the task number :(";
        }
    }

    /**
     * Processes the user's input when the todo Keyword is encountered and returns the todo's description.
     * @param toDoStrings An array containing the words from the user's input when the todo Keyword is encountered.
     * @return The todo's description.
     * @throws EmptyDescriptionException If the todo's description is an empty string.
     */
    public String processToDoString(String... toDoStrings) throws EmptyDescriptionException {
        if (toDoStrings.length == 1) {
            throw new EmptyDescriptionException();
        }

        List<String> list = new ArrayList<>(Arrays.asList(toDoStrings));
        list.remove(0);

        return String.join(" ", list);
    }

    /**
     * Processes the user's input when the deadline Keyword is encountered and returns
     * the deadline's description and deadline.
     * @param deadlineStrings An array containing the words from the user's input
     *     when the deadline Keyword is encountered.
     * @return An array containing the deadlines's description and deadline.
     * @throws EmptyDescriptionException If the deadline's description is an empty string.
     * @throws EmptyDeadlineException If the deadline's deadline is an empty string.
     */
    public String[] processDeadlineString(String[] deadlineStrings) throws EmptyDescriptionException,
            EmptyDeadlineException {
        assert deadlineStrings != null : "Input array should not be null";
        assert deadlineStrings.length > 1 : "Input should contain more than keyword";

        String[] deadlineOutputs = new String[2];
        StringBuilder description = new StringBuilder();
        StringBuilder deadline = new StringBuilder();
        boolean beforeDeadline = true;

        for (int i = 1; i < deadlineStrings.length; i++) {
            if (deadlineStrings[i].equals("/by")) {
                beforeDeadline = false;
            } else if (beforeDeadline) {
                description.append(deadlineStrings[i] + " ");
            } else {
                deadline.append(deadlineStrings[i] + " ");
            }
        }

        if (description.length() == 0) {
            throw new EmptyDescriptionException();
        } else if (deadline.length() == 0) {
            throw new EmptyDeadlineException();
        }

        deadlineOutputs[0] = description.deleteCharAt(description.length() - 1).toString();
        deadlineOutputs[1] = deadline.deleteCharAt(deadline.length() - 1).toString();

        return deadlineOutputs;
    }

    /**
     * Processes the user's input when the event Keyword is encountered and
     * returns the event's description, from and to.
     * @param eventStrings An array containing the words from the user's input when the event Keyword is encountered.
     * @return An array containing the event's description, from and to.
     * @throws EmptyDescriptionException If the event's description is an empty string.
     * @throws EmptyFromException If the event's from is an empty string.
     * @throws EmptyToException If the event's to is an empty string.
     * @throws DateTimeConflictException If the to is before the from.
     */
    public String[] processEventString(String[] eventStrings) throws EmptyDescriptionException,
            EmptyFromException, EmptyToException, DateTimeConflictException {
        assert eventStrings != null : "Input array should not be null";
        assert eventStrings.length > 1 : "Input should contain more than keyword";

        String[] eventOutputs = new String[3];
        StringBuilder description = new StringBuilder();
        StringBuilder from = new StringBuilder();
        StringBuilder to = new StringBuilder();
        boolean isBeforeFrom = true;
        boolean isBeforeTo = true;

        for (int i = 1; i < eventStrings.length; i++) {
            if (eventStrings[i].equals("/from")) {
                isBeforeFrom = false;
            } else if (eventStrings[i].equals("/to")) {
                isBeforeTo = false;
            } else if (isBeforeFrom) {
                description.append(eventStrings[i] + " ");
            } else if (isBeforeTo) {
                from.append(eventStrings[i] + " ");
            } else {
                to.append(eventStrings[i] + " ");
            }
        }

        if (description.length() == 0) {
            throw new EmptyDescriptionException();
        } else if (from.length() == 0) {
            throw new EmptyFromException();
        } else if (to.length() == 0) {
            throw new EmptyToException();
        }

        eventOutputs[0] = description.deleteCharAt(description.length() - 1).toString();
        eventOutputs[1] = from.deleteCharAt(from.length() - 1).toString();
        eventOutputs[2] = to.deleteCharAt(to.length() - 1).toString();

        return eventOutputs;
    }

    /**
     * Handles the user's input when the mark Keyword is encountered and returns the response string.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return Response string generated by marking the task.
     * @throws EmptyIndexException If the index to be marked is not specified.
     * @throws IndexDoesNotExistException If the index is out of bounds of the taskList.
     * @throws TaskAlreadyMarkedException If the task specified is already done.
     */
    public String handleMark(String[] splitUserInput, TaskList taskList) throws EmptyIndexException,
            IndexDoesNotExistException, TaskAlreadyMarkedException {
        int index;

        if (splitUserInput.length == 1) {
            throw new EmptyIndexException();
        }

        index = Integer.parseInt(splitUserInput[1]) - 1;

        return taskList.mark(index);
    }

    /**
     * Handles the user's input when the unmark Keyword is encountered and returns the response string.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return Response string generated by unmarking the task.
     * @throws EmptyIndexException If the index to be unmarked is not specified.
     * @throws IndexDoesNotExistException If the index is out of bounds of the taskList.
     * @throws TaskAlreadyUnmarkedException If the task specified is already marked as not done.
     */
    public String handleUnmark(String[] splitUserInput, TaskList taskList) throws EmptyIndexException,
            IndexDoesNotExistException, TaskAlreadyUnmarkedException {
        int index;

        if (splitUserInput.length == 1) {
            throw new EmptyIndexException();
        }

        index = Integer.parseInt(splitUserInput[1]) - 1;

        return taskList.unmark(index);
    }

    /**
     * Handles the user's input when the delete Keyword is encountered and returns the response string.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return Response string generated by deleting the task.
     * @throws EmptyIndexException If the index to be deleted is not specified.
     * @throws IndexDoesNotExistException If the index is out of bounds of the taskList.
     */
    public String handleDelete(String[] splitUserInput, TaskList taskList) throws EmptyIndexException,
            IndexDoesNotExistException {
        int index;

        if (splitUserInput.length == 1) {
            throw new EmptyIndexException();
        }

        index = Integer.parseInt(splitUserInput[1]) - 1;

        return taskList.delete(index);
    }

    /**
     * Handles the user's input when the find Keyword is encountered and returns the response string.
     * @param splitUserInput An array containing the words in the user's input.
     * @param taskList A TaskList object used to manage TooDoo's task list.
     * @return Response string generated by finding the task.
     * @throws EmptyRegexException If the regex to find is not specified.
     */
    public String handleFind(String[] splitUserInput, TaskList taskList) throws EmptyRegexException {
        if (splitUserInput.length == 1) {
            throw new EmptyRegexException();
        }
        return taskList.find(splitUserInput[1]);
    }
}


